services:
  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    restart: unless-stopped

  client:
    build:
      context: ./client
    ports:
      - "5173:5173"
    environment:
      - VITE_BASE_URL=http://localhost:8080/api/v1
    depends_on:
      - server
